# Generated by Django 6.0 on 2025-12-31 19:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water supply', 'Water supply')], max_length=12)),
                ('regulation_name', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('other', 'Other')], max_length=15)),
                ('user', models.OneToOneField(default='Deleted User', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_code', models.CharField(max_length=150)),
                ('course_credit', models.CharField(max_length=150)),
                ('course_description', models.TextField()),
                ('education', models.ForeignKey(default='Deleted Education Level', on_delete=django.db.models.deletion.SET_DEFAULT, to='mainApp.education')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1500)),
                ('description', models.TextField()),
                ('save_flag', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=30)),
                ('view_flag', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField()),
                ('user', models.ForeignKey(default='Deleted User', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegulationKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('regulation', models.ForeignKey(default='Deleted keyword', on_delete=django.db.models.deletion.SET_DEFAULT, to='mainApp.regulation')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default='Deleted User', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semister', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('firfth', 'Firfth'), ('sixth', 'Sixth'), ('seventh', 'Seventh'), ('eighth', 'Eighth')], max_length=15)),
                ('education', models.ForeignKey(default='Deleted Education Level', on_delete=django.db.models.deletion.SET_DEFAULT, to='mainApp.education')),
            ],
        ),
    ]
