# Generated by Django 6.0 on 2026-01-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='No question', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_level',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Regulations and Laws', 'Regulations and Laws'), ('Methodology', 'Methodology'), ('Learning Resources', 'Learning Resources'), ('Career Advice', 'Career Advice'), ('Technical', 'Issues')], max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
