# Generated by Django 6.0 on 2026-01-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_question_question_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(default='Not included', max_length=100),
        ),
    ]
