# Generated by Django 6.0 on 2026-01-03 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_education_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_file',
            field=models.FileField(default='No file', upload_to='documents/notices/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'ppt', 'pptx'])]),
        ),
        migrations.AddField(
            model_name='regulation',
            name='regulation_file',
            field=models.FileField(default='No file', upload_to='documents/regulations/'),
        ),
        migrations.AlterField(
            model_name='semister',
            name='semister',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Firfth', 'Firfth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth')], max_length=15),
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='No one', max_length=200)),
                ('question', models.ForeignKey(default='Question Deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='mainApp.question')),
            ],
        ),
    ]
