# Generated by Django 6.0 on 2026-01-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_course_course_file_regulation_regulation_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
    ]
