# Generated by Django 6.0 on 2026-01-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default='Not given', max_length=1500),
        ),
    ]
