# Generated by Django 6.0 on 2026-01-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
    ]
