# Generated by Django 6.0 on 2026-01-04 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_remove_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.question'),
        ),
    ]
