# Generated by Django 6.0 on 2026-01-12 14:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_course_options_course_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['education_level', 'course_code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='education',
        ),
        migrations.AddField(
            model_name='course',
            name='education_level',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('Other', 'Other')], default='Degree', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_file',
            field=models.FileField(default='No file', upload_to='documents/courses/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'ppt', 'pptx'])]),
        ),
    ]
